proxmox_cluster: pve

proxmox_root: "root@pam"
## Read the root password from the vault and copy here at runtime:
proxmox_root_password: "{{ vault_proxmox_root_password }}"
core_ssh_keys: "{{ vault_core_ssh_keys }}"
proxmox_domain: "app.lan.rymcg.tech"
proxmox_master_node: nuc1
proxmox_public_interface: br0
promox_public_network: 192.168.3.0/24
proxmox_master_ip: 192.168.3.14
proxmox_public_netmask: 255.255.255.0
proxmox_public_gateway: 192.168.3.1

proxmox_external_client_subnets:
  - 192.168.2.101/32
  - 192.168.2.110/32

## TODO: Setup TLS before going to PROD
proxmox_verify_ssl: False

proxmox_kvm_admin: "root@pam"
## Read the root password from the vault and copy here at runtime:
proxmox_kvm_admin_password: "{{ vault_proxmox_root_password }}"

## Proxmox node ids are used in automagic IP assignment for vm subnets:
## Examples: vmbr1 = 10.10.1.0/24
##            nuc1 = 10.10.1.1
##            nuc2 = 10.10.1.2
##            nuc3 = 10.10.1.3
##
##           vmbr2 = 10.10.2.0/24
##            nuc1 = 10.10.2.1
##            nuc2 = 10.10.2.2
##            nuc3 = 10.10.2.3
##
proxmox_nodes:
  nuc1:
    id: 1
  nuc2:
    id: 2
  nuc3:
    id: 3

## Virtual Machine subnets:
## cluster=False prevents routes between hosts for same subnet
## You should keep these sequential for vmbr0, vmbr1, etc...
proxmox_vm_subnets:
  - network: 10.10.0.0/24
    interface: vmbr0
    cluster: False
  - network: 10.10.1.0/24
    interface: vmbr1
  - network: 10.10.2.0/24
    interface: vmbr2
  - network: 10.10.3.0/24
    interface: vmbr3
  - network: 10.10.4.0/24
    interface: vmbr4
  - network: 10.10.5.0/24
    interface: vmbr5
  - network: 10.10.6.0/24
    interface: vmbr6
  - network: 10.10.7.0/24
    interface: vmbr7
  - network: 10.10.8.0/24
    interface: vmbr8
  - network: 10.10.9.0/24
    interface: vmbr9

### Proxmox KVM instance sizes:
### (names are loosly based off AWS instance sizes)
proxmox_instance_sizes:
  m1.nano:
    ram: 0.5
    cpu: 1
  m1.micro:
    ram: 1
    cpu: 1
  m1.small:
    ram: 2
    cpu: 2
  m1.medium:
    ram: 4
    cpu: 2
  m1.large:
    ram: 8
    cpu: 2
  m1.xlarge:
    ram: 16
    cpu: 4
  c1.small:
    ram: 2
    cpu: 4
  c1.medium:
    ram: 4
    cpu: 4
  c1.large:
    ram: 8
    cpu: 4
  c1.xlarge:
    ram: 16
    cpu: 6

ubuntu_bionic_cloud_image_url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
ubuntu_bionic_cloud_image: /mnt/pve/cephfs/template/iso/bionic-server-cloudimg-amd64.img

proxmox_template_ids:
  ubuntu_bionic:
    nuc1: 9000
    nuc2: 9001
    nuc3: 9002

