- name: Get promox API auth token
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/access/ticket"
    method: POST
    validate_certs: "{{ proxmox_verify_ssl }}"
    body_format: form-urlencoded
    body:
      username: "{{ proxmox_root }}"
      password: "{{ proxmox_root_password }}"
  register: proxmox_auth_token

- name: KVM test instance 110
  include_role:
    name: kvm_instance
  vars:
    id: 110
    host: nuc1
    name: test
    size: m1.small
    volumes:
      root: 20G
    sshkeys: "{{ core_ssh_keys }}"

- name: KVM test instance 111
  include_role:
    name: kvm_instance
  vars:
    id: 111
    host: nuc2
    name: test
    size: m1.small
    volumes:
      root: 20G
    sshkeys: "{{ core_ssh_keys }}"
