- name: Create test KVM
  include_role:
    name: kvm_clone
  vars:
    id: 100
    name: testguy
    template: ubuntu-bionic
    ip_address: 10.10.1.100/24
    gateway: 10.10.1.1
    state: started
    memory: 2048
    cores: 2
    disk_size: 10G
    node: nuc1
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFn5eqeYFpM2srhsJ+vBG35oQvnRdnxsjm9ZEr4UDOdZkUVVUzXCF3K1BJM45/t8KtfQjsUUWWBrX0UdSevut8xkTwJ+0W3TEQ11P28BD46BRT3axkghomm+zT7uHCzNHg2K0t1ysP/YyHaq6RgixvWlv+x7hfD2+2fPS7lCJZJReCxSF6rf+7JyhyR2xTkA6WVTIWTtrNgrDF1mAN6C4/uKqzoDS0tlsfutqmFaIbWBo1Tk2Czqpfn5WRy+zseUr7azFkxLQEMSnHLeyJLVd+AljMe6dh5W5cYuta5sThp+S2QEyxuZQACLaf4XduXxoOlZxkTF0c/1Oc8eb+psSYVbOlkh+iQkAP9q/4XqMe6Wq/l1+XF5m+1JcF6SWqGWFByco/oqaLbeBy5NLn0Di3acM2V0tuoT4RmKQOw42Fxg/uFkzZZ6CDX75VBdDckGGJSw0lvkDKrVIZokmsXCXUauXAgKkl9gl/4Vl2s9VoX9hCMvB/reB7WVe91Thgnas= ryan@t440s"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC08pedOWo2IY3uQIqIBrEUKDCHZSVyPYNJBzAwRfemKNbVXZAwkeI1lDVmnEBdCmFGT86df8mMdH6/DVYwpoLdcBT+vaacxMtU9aqz8ItCbtOFLlKOJfWceuwMnrjljQK9GWqWmTpGYcXOctIfgdRikhMc+T6H+QqKNTeR0R+xJUFjujsNgSlxTKbuwPgnw9oXOa7Wj4jGfns54kOi4hu9qXTQXP6qZs3xy45rxU1cNcu6VIa1gpPIlB47HxWn869zc3aYk/QIWYI0KnT+OFh9XvvB9LYzBExoEzr7ll0Zk0b41uvQgbsFLPIkTZ5nxW+xFxkwJS9udI4d71+kz13x ryan@Maldek"

- name: Create test KVM 2
  include_role:
    name: kvm_clone
  vars:
    id: 101
    name: testguy2
    template: ubuntu-bionic
    ip_address: 10.10.1.101/24
    gateway: 10.10.1.1
    state: started
    memory: 2048
    cores: 2
    disk_size: 10G
    node: nuc1
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFn5eqeYFpM2srhsJ+vBG35oQvnRdnxsjm9ZEr4UDOdZkUVVUzXCF3K1BJM45/t8KtfQjsUUWWBrX0UdSevut8xkTwJ+0W3TEQ11P28BD46BRT3axkghomm+zT7uHCzNHg2K0t1ysP/YyHaq6RgixvWlv+x7hfD2+2fPS7lCJZJReCxSF6rf+7JyhyR2xTkA6WVTIWTtrNgrDF1mAN6C4/uKqzoDS0tlsfutqmFaIbWBo1Tk2Czqpfn5WRy+zseUr7azFkxLQEMSnHLeyJLVd+AljMe6dh5W5cYuta5sThp+S2QEyxuZQACLaf4XduXxoOlZxkTF0c/1Oc8eb+psSYVbOlkh+iQkAP9q/4XqMe6Wq/l1+XF5m+1JcF6SWqGWFByco/oqaLbeBy5NLn0Di3acM2V0tuoT4RmKQOw42Fxg/uFkzZZ6CDX75VBdDckGGJSw0lvkDKrVIZokmsXCXUauXAgKkl9gl/4Vl2s9VoX9hCMvB/reB7WVe91Thgnas= ryan@t440s"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC08pedOWo2IY3uQIqIBrEUKDCHZSVyPYNJBzAwRfemKNbVXZAwkeI1lDVmnEBdCmFGT86df8mMdH6/DVYwpoLdcBT+vaacxMtU9aqz8ItCbtOFLlKOJfWceuwMnrjljQK9GWqWmTpGYcXOctIfgdRikhMc+T6H+QqKNTeR0R+xJUFjujsNgSlxTKbuwPgnw9oXOa7Wj4jGfns54kOi4hu9qXTQXP6qZs3xy45rxU1cNcu6VIa1gpPIlB47HxWn869zc3aYk/QIWYI0KnT+OFh9XvvB9LYzBExoEzr7ll0Zk0b41uvQgbsFLPIkTZ5nxW+xFxkwJS9udI4d71+kz13x ryan@Maldek"
