- name: Create test KVM
  include_role:
    name: kvm_clone
  vars:
    id: 100
    name: testguy
    template: ubuntu-bionic
    ip_address: 10.10.0.2/24
    gateway: 10.10.0.1
    state: started
    memory: 2048
    cores: 2
    node: nuc1
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFn5eqeYFpM2srhsJ+vBG35oQvnRdnxsjm9ZEr4UDOdZkUVVUzXCF3K1BJM45/t8KtfQjsUUWWBrX0UdSevut8xkTwJ+0W3TEQ11P28BD46BRT3axkghomm+zT7uHCzNHg2K0t1ysP/YyHaq6RgixvWlv+x7hfD2+2fPS7lCJZJReCxSF6rf+7JyhyR2xTkA6WVTIWTtrNgrDF1mAN6C4/uKqzoDS0tlsfutqmFaIbWBo1Tk2Czqpfn5WRy+zseUr7azFkxLQEMSnHLeyJLVd+AljMe6dh5W5cYuta5sThp+S2QEyxuZQACLaf4XduXxoOlZxkTF0c/1Oc8eb+psSYVbOlkh+iQkAP9q/4XqMe6Wq/l1+XF5m+1JcF6SWqGWFByco/oqaLbeBy5NLn0Di3acM2V0tuoT4RmKQOw42Fxg/uFkzZZ6CDX75VBdDckGGJSw0lvkDKrVIZokmsXCXUauXAgKkl9gl/4Vl2s9VoX9hCMvB/reB7WVe91Thgnas= ryan@t440s"

