## Only modify KVM if it doesn't already exist:
- name: "Get KVM id={{ id }} state"
  proxmox_kvm:
    api_user: "{{ proxmox_kvm_admin }}"
    api_password: "{{ proxmox_kvm_admin_password }}"
    api_host: "{{ proxmox_master_node }}"
    node: "{{ node }}"
    vmid: "{{ id }}"
    state: current
  register: kvm_state
  ignore_errors: true

- name: "Clone KVM template={{ template }} id={{ id }}"
  when: kvm_state.failed
  proxmox_kvm:
    api_user: "{{ proxmox_kvm_admin }}"
    api_password: "{{ proxmox_kvm_admin_password }}"
    api_host: "{{ proxmox_master_node }}"
    node: "{{ node }}"
    clone: "{{ template }}"
    newid: "{{ id }}"
    name: "{{ name }}"
    full: 0

- name: "Configure KVM id={{ id }}"
  when: kvm_state.failed
  proxmox_kvm:
    api_user: "{{ proxmox_kvm_admin }}"
    api_password: "{{ proxmox_kvm_admin_password }}"
    api_host: "{{ proxmox_master_node }}"
    node: "{{ node }}"
    name: "{{ name }}"
    vmid: "{{ id }}"
    cores: "{{ cores }}"
    sockets: "{{ sockets }}"
    memory: "{{ memory }}"
    ciuser: "{{ ciuser }}"
    nameserver: "{{ nameserver }}"
    ipconfig0: "gw={{ gateway }},ip={{ ip_address }}"
    searchdomain: "{{ searchdomain }}"
    sshkeys: "{{ \"\n\".join(sshkeys)|urlencode|replace('/','%2F') }}"
    update: yes

- name: Get promox master API auth token
  when: kvm_state.failed
  uri:
    url: "https://{{ proxmox_master_node }}:8006/api2/json/access/ticket"
    method: POST
    validate_certs: False
    body_format: form-urlencoded
    body:
      username: "{{ proxmox_root }}"
      password: "{{ proxmox_root_password }}"
  register: proxmox_master_auth_token


- name: "Resize disk of KVM id={{ id }}"
  when: kvm_state.failed
  uri:
    url: "https://{{ proxmox_master_node }}:8006/api2/json/nodes/{{ node }}/qemu/{{ id }}/resize"
    validate_certs: "{{ proxmox_verify_ssl }}"
    method: PUT
    headers: 
      Cookie: "PVEAuthCookie={{ proxmox_master_auth_token.json.data.ticket }}"
      CSRFPreventionToken: "{{ proxmox_master_auth_token.json.data.CSRFPreventionToken }}"
    body_format: form-urlencoded
    body:
      disk: "scsi0"
      size: "{{ disk_size }}"

- name: "Set KVM id={{ id }} state={{state}}"
  proxmox_kvm:
    api_user: "{{ proxmox_kvm_admin }}"
    api_password: "{{ proxmox_kvm_admin_password }}"
    api_host: "{{ proxmox_master_node }}"
    vmid: "{{ id }}"
    state: "{{ state }}"
